# Generated by Django 3.2.8 on 2021-11-12 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='waktuPosting',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
